#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Preparing to commit: Styling your project 👷‍♂️🏗️'
echo 'Please be patient, this process may take a moment...'
npm run pre-commit-lint

echo '\n🏗️👷 Preparing to commit: Checking types in your project 👷‍♂️🏗️'
echo 'Please be patient, this process may take a moment...'
npm run check-types
