#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling your project before committing👷‍♂️🏗️'
echo 'please be patient, this may take a while...'
npm run pre-commit-lint

echo '🏗️👷 Check types your project👷‍♂️🏗️'
echo 'please be patient, this may take a while...'
npm run check-types

echo '🏗️👷 Check commit message 👷‍♂️🏗️'
echo 'please be patient, this may take a while...'
